apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      serviceAccountName: nginx-proxy-sa
      imagePullSecrets:
      - name: ecr-secret
      containers:
        - name: nginx
          image: 099210689252.dkr.ecr.ap-south-1.amazonaws.com/flask-nginx-app:nginx-dev
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: flask-app
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

