apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::099210689252:role/flask-eks-cluster-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::099210689252:role/github-actions-eks-role
      username: github-actions
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::099210689252:role/flask-eks-cluster-node-role\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n\n- rolearn: arn:aws:iam::099210689252:role/github-actions-eks-role\n  username: github-actions\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2025-12-27T11:57:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "84668"
  uid: 0fb97f61-fb7d-4eb8-b234-2f0fda260a16
